# @package _group_
# ========================================================================
# Hyperparameters for classic Nature DQN, matched to
# Rainbow (Hessel et al., 2018) for comparison in Dopamine framework
# Github: https://github.com/google/dopamine/
#         blob/baf4b8273dce64fcd865185b29f22070a5d96a35/
#         dopamine/agents/dqn/configs/dqn.gin
# ========================================================================
cls_string: 'RMSprop'
kwargs:
    lr: 0.00025
    alpha: 0.95
    momentum: 0.0
    eps: 0.00001
    centered: True
